### ISSUE TITLE
Disallow duplicates

### ISSUE THREAD

**Issue by Morgy93** [elgentos/EasyAttributes#1]
Hello,

somehow it is possible to add as many duplicates as you want.
I don't know how, because usually that's not even possible within Magento, but I hope this gets fixed.
<img width="143" alt="capture" src="https://cloud.githubusercontent.com/assets/7961978/12225408/4ae31766-b80a-11e5-8007-bb3cc1cb2e7a.PNG">

Awesome extension by the way!

**Comment by peterjaap** [comment]
Duplicate option values are certainly possible with default Magento, there is no protection on it. That is pretty much the whole reason why the merge functionality in this extension exists.

If you have imported the above list using the textarea that this extension adds, you could undupe the list by using www.dupe-checker.com.
